CREATE TABLE [dbo].[Equipments]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Name] NVARCHAR(100) NOT NULL, 
	[UOM] INT NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,

	CONSTRAINT [FK_Equipments_UOM] FOREIGN KEY ([UOM]) REFERENCES [UOM]([Id])
)
