CREATE TABLE [dbo].[Labours]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Name] NVARCHAR(100) NOT NULL, 
	[UOM] INT NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,

	CONSTRAINT [FK_Labours_UOM] FOREIGN KEY ([UOM]) REFERENCES [UOM]([Id])
)
