CREATE TABLE [dbo].[UOM]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Name] NVARCHAR(100) NOT NULL, 
	[UOM] NVARCHAR(20) NOT NULL, 
	[Type] NVARCHAR(100) NOT NULL, 
	[IsCost] BIT NOT NULL DEFAULT 0,
	[UsedInMaterials] BIT NOT NULL DEFAULT 0,
	[UsedInEquipment] BIT NOT NULL DEFAULT 0,
	[UsedInLabour] BIT NOT NULL DEFAULT 0,
	[MeasurementId] INT NULL,
	[Description] NVARCHAR(500) NOT NULL 
)
